/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
  id INT NOT NULL    GENERATED ALWAYS AS IDENTITY,
  name       TEXT,
  date_of_birth      DATE,
  escape_attempts    INT,
  neutered   BOOLEAN,
  weight_kg  DECIMAL(5, 2)
);


ALTER TABLE animals
ADD COLUMN species TEXT;


CREATE TABLE owners (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
full_name TEXT,
age INT
);

CREATE TABLE species (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name TEXT
);

ALTER TABLE animals
DROP COLUMN species;
ALTER TABLE animals
ADD COLUMN species_id INT CONSTRAINT species REFERENCES species(id),
ADD COLUMN owner_id INT CONSTRAINT owners REFERENCES owners(id);

